data_file = 'public/data_dev.json'
public_dir = 'public'
qr_dir = 'public/qr_dev'

[verifiers.geartech]
name = 'Gear Technologies'
public_key = '3cdf41f721ca5269ae0eeb4343cb60721fd8cbac7022328cf959d7c3e728d969'

[[chains]]
name = 'vara'
title = 'Vara Network'
color = '#00a87a'
icon = 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/gradient/Polkadot.svg'
rpc_endpoints = [
    'wss://rpc.vara-network.io/'
]
testnet = false
verifier = 'geartech'