data_file = 'public/data.json'
public_dir = 'public'
qr_dir = 'public/qr'

[verifiers.geartech]
name = 'Gear Technologies'
public_key = '3cdf41f721ca5269ae0eeb4343cb60721fd8cbac7022328cf959d7c3e728d969'

[[chains]]
name = 'vara'
title = 'Vara Network'
color = '#00a87a'
icon = '/img/vara-logo.svg'
rpc_endpoints = [
    'wss://rpc.vara-network.io/'
]
testnet = false
verifier = 'geartech'
